apiVersion: v2
name: redis-notebook
description: OpenShift AI Notebook with Redis semantic cache and git clone of the Redis Cost Reduction demo
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - openshift
  - openshift-ai
  - jupyter
  - redis
home: https://github.com/rh-ai-quickstart/Reducing-costs-of-AI-with-Redis-Labs
maintainers:
  - name: Red Hat AI Quickstart Team
dependencies:
  - name: redis-operator
    version: 0.24.0
    repository: https://ot-container-kit.github.io/helm-charts/
    condition: redis.operator.enabled
  - name: redis
    alias: redisData
    version: 0.16.9
    repository: https://ot-container-kit.github.io/helm-charts/
    condition: redis.enabled
