{{- if and .Values.openshiftAI.operator.enabled .Values.openshiftAI.operator.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.openshiftAI.operator.namespace | quote }}
  labels:
    {{- include "redis-notebook.openshiftAIOperatorLabels" . | nindent 4 }}
{{- end }}
